### ISSUE TITLE
Deleting entire word

### ISSUE THREAD

**Issue by anipr2002** [1r00t/typr#21]
add support for ctrl+delete to delete the entire word.

**Comment by anipr2002** [comment]
Hey, @1r00t is it okay for me to work on this issue? I am new to open source and would like this to be my first contribution :)

**Comment by 1r00t** [comment]
Sure why not, if you'd like to! You can create a pull request

**Comment by anipr2002** [comment]
I have to completed everything except handling multiple input (i.e ctrl+backspace). Can you advice how to go about this problem.
Thank you.

**Comment by anipr2002** [comment]
I have sent a PR. Can you please review.

**Comment by 1r00t** [comment]
#23
